-- MySQL Script generated by MySQL Workbench
-- Thu Feb  9 16:26:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sexo` (
  `idSexo` INT NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Naturalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Naturalidade` (
  `idNaturalidade` INT NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNaturalidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado Civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado Civil` (
  `idEstado Civil` INT NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado Civil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Escolaridade` (
  `idEscolaridade` INT NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEscolaridade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuário` (
  `CPF` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Estado Civil_idEstado Civil` INT NOT NULL,
  `Naturalidade_idNaturalidade` INT NOT NULL,
  `Sexo_idSexo` INT NOT NULL,
  `Escolaridade_idEscolaridade` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Data de Nascimento` VARCHAR(45) NOT NULL,
  `Identidade` INT UNSIGNED NOT NULL,
  `Filiação` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`),
  CONSTRAINT `fk_Usuário_Sexo1`
    FOREIGN KEY (`Sexo_idSexo`)
    REFERENCES `mydb`.`Sexo` (`idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuário_Naturalidade1`
    FOREIGN KEY (`Naturalidade_idNaturalidade`)
    REFERENCES `mydb`.`Naturalidade` (`idNaturalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuário_Estado Civil1`
    FOREIGN KEY (`Estado Civil_idEstado Civil`)
    REFERENCES `mydb`.`Estado Civil` (`idEstado Civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuário_Escolaridade1`
    FOREIGN KEY (`Escolaridade_idEscolaridade`)
    REFERENCES `mydb`.`Escolaridade` (`idEscolaridade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`País`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`País` (
  `idPaís` INT NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPaís`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UF` (
  `idEstado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `País_idPaís` INT NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`),
  CONSTRAINT `fk_UF_País1`
    FOREIGN KEY (`País_idPaís`)
    REFERENCES `mydb`.`País` (`idPaís`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `idCidade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UF_idEstado` INT UNSIGNED NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCidade`),
  CONSTRAINT `fk_Cidade_UF1`
    FOREIGN KEY (`UF_idEstado`)
    REFERENCES `mydb`.`UF` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bairro` (
  `idBairro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cidade_idCidade` INT UNSIGNED NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBairro`),
  CONSTRAINT `fk_Bairro_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `mydb`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Endereço` (
  `idTipo_Endereço` INT NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_Endereço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereço` (
  `idEndereço` INT NOT NULL AUTO_INCREMENT,
  `Bairro_idBairro` INT UNSIGNED NOT NULL,
  `Tipo_Endereço_idTipo_Endereço` INT NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Complemento` VARCHAR(45) NOT NULL,
  `Número` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEndereço`),
  CONSTRAINT `fk_Endereço_Bairro1`
    FOREIGN KEY (`Bairro_idBairro`)
    REFERENCES `mydb`.`Bairro` (`idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereço_Tipo_Endereço1`
    FOREIGN KEY (`Tipo_Endereço_idTipo_Endereço`)
    REFERENCES `mydb`.`Tipo_Endereço` (`idTipo_Endereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NOT NULL,
  `Salario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transação` (
  `idTransação` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTransação`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conta` (
  `idConta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Transação_idTransação` INT UNSIGNED NOT NULL,
  `Valor` FLOAT UNSIGNED NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idConta`),
  CONSTRAINT `fk_Conta_Transação1`
    FOREIGN KEY (`Transação_idTransação`)
    REFERENCES `mydb`.`Transação` (`idTransação`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Status` (
  `idStatus` INT UNSIGNED NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mesa` (
  `idMesa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `Mesa_idMesa` INT UNSIGNED NOT NULL,
  `Conta_idConta` INT UNSIGNED NOT NULL,
  `Status_idStatus` INT UNSIGNED NOT NULL,
  `Horário` TIME NOT NULL,
  `Data` VARCHAR(45) NOT NULL,
  `Observação` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPedido`, `Mesa_idMesa`, `Conta_idConta`, `Status_idStatus`),
  CONSTRAINT `fk_Pedido_Conta1`
    FOREIGN KEY (`Conta_idConta`)
    REFERENCES `mydb`.`Conta` (`idConta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Status1`
    FOREIGN KEY (`Status_idStatus`)
    REFERENCES `mydb`.`Status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Mesa1`
    FOREIGN KEY (`Mesa_idMesa`)
    REFERENCES `mydb`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Usuário_CPF` INT UNSIGNED NOT NULL,
  `Mesa_idMesa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCliente`, `Usuário_CPF`, `Mesa_idMesa`),
  CONSTRAINT `fk_Cliente_Usuário1`
    FOREIGN KEY (`Usuário_CPF`)
    REFERENCES `mydb`.`Usuário` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Mesa1`
    FOREIGN KEY (`Mesa_idMesa`)
    REFERENCES `mydb`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Quantidade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingredientes` (
  `idIngredientes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Estoque_idEstoque` INT UNSIGNED NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIngredientes`),
  CONSTRAINT `fk_Ingredientes_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prato` (
  `idPrato` INT NOT NULL AUTO_INCREMENT,
  `Pedido_idPedido` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  `Ingredientes_idIngredientes` INT UNSIGNED NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Valor` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPrato`),
  CONSTRAINT `fk_Prato_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prato_Ingredientes1`
    FOREIGN KEY (`Ingredientes_idIngredientes`)
    REFERENCES `mydb`.`Ingredientes` (`idIngredientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prato_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Telefone` (
  `idTipo_Telefone` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_Telefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `idTelefone` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Tipo_Telefone_idTipo_Telefone` INT UNSIGNED NOT NULL,
  `DDD` INT UNSIGNED NOT NULL,
  `Número` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idTelefone`),
  CONSTRAINT `fk_Telefone_Tipo_Telefone1`
    FOREIGN KEY (`Tipo_Telefone_idTipo_Telefone`)
    REFERENCES `mydb`.`Tipo_Telefone` (`idTipo_Telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_E-mail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_E-mail` (
  `idTipo_E-mail` INT NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_E-mail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`E-mail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`E-mail` (
  `idE-mail` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Tipo_E-mail_idTipo_E-mail` INT NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idE-mail`),
  CONSTRAINT `fk_E-mail_Tipo_E-mail1`
    FOREIGN KEY (`Tipo_E-mail_idTipo_E-mail`)
    REFERENCES `mydb`.`Tipo_E-mail` (`idTipo_E-mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `Usuário_CPF` INT UNSIGNED NOT NULL,
  `Mesa_idMesa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idFuncionario`, `Usuário_CPF`, `Mesa_idMesa`),
  CONSTRAINT `fk_Funcionario_Usuário1`
    FOREIGN KEY (`Usuário_CPF`)
    REFERENCES `mydb`.`Usuário` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Mesa1`
    FOREIGN KEY (`Mesa_idMesa`)
    REFERENCES `mydb`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereço_has_Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereço_has_Usuário` (
  `Endereço_idEndereço` INT NOT NULL,
  `Usuário_CPF` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Endereço_idEndereço`, `Usuário_CPF`),
  CONSTRAINT `fk_Endereço_has_Usuário_Endereço1`
    FOREIGN KEY (`Endereço_idEndereço`)
    REFERENCES `mydb`.`Endereço` (`idEndereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereço_has_Usuário_Usuário1`
    FOREIGN KEY (`Usuário_CPF`)
    REFERENCES `mydb`.`Usuário` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`E-mail_has_Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`E-mail_has_Usuário` (
  `E-mail_idE-mail` INT UNSIGNED NOT NULL,
  `Usuário_CPF` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`E-mail_idE-mail`, `Usuário_CPF`),
  CONSTRAINT `fk_E-mail_has_Usuário_E-mail1`
    FOREIGN KEY (`E-mail_idE-mail`)
    REFERENCES `mydb`.`E-mail` (`idE-mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_E-mail_has_Usuário_Usuário1`
    FOREIGN KEY (`Usuário_CPF`)
    REFERENCES `mydb`.`Usuário` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuário_has_Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuário_has_Telefone` (
  `Usuário_CPF` INT UNSIGNED NOT NULL,
  `Telefone_idTelefone` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Usuário_CPF`, `Telefone_idTelefone`),
  CONSTRAINT `fk_Usuário_has_Telefone_Usuário1`
    FOREIGN KEY (`Usuário_CPF`)
    REFERENCES `mydb`.`Usuário` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuário_has_Telefone_Telefone1`
    FOREIGN KEY (`Telefone_idTelefone`)
    REFERENCES `mydb`.`Telefone` (`idTelefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico_Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historico_Cargo` (
  `idHistorico_Cargo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Funcionario_idFuncionario` INT NOT NULL,
  `Cargo_idCargo` INT UNSIGNED NOT NULL,
  `Inicio` VARCHAR(45) NOT NULL,
  `Fim` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHistorico_Cargo`, `Funcionario_idFuncionario`),
  CONSTRAINT `fk_Historico_Cargo_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `mydb`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historico_Cargo_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario_has_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario_has_Pedido` (
  `Funcionario_idFuncionario` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`Funcionario_idFuncionario`, `Pedido_idPedido`),
  CONSTRAINT `fk_Funcionario_has_Pedido_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `mydb`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_has_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_has_Pedido` (
  `Cliente_idCliente` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Pedido_idPedido`),
  CONSTRAINT `fk_Cliente_has_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
